version: '3.7'
services:
  demo-redis:
    container_name: demo-redis
    image: redis:latest
    ports:
      - "6379:6379"
    command:
      --requirepass ${REDIS_HOST_PASSWORD}
    restart: always
    networks:
      - demo-network
  demo-mongodb:
    container_name: demo-mongodb
    image: mongo:latest
    env_file:
      - .env
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - demo-network
  demo-nats:
    container_name: demo-nats
    image: nats:latest
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    restart: always
    hostname: nats-server
    networks:
      - demo-network
volumes:
  mongo-data:
networks:
  demo-network: